name = "jsrpc-react-example"
main = "src/worker.ts"
compatibility_date = "2024-09-01"

[assets]
directory = "web/dist"

[vars]
# Optional per-method artificial delays (ms)
DELAY_AUTH_MS = 80
DELAY_PROFILE_MS = 120
DELAY_NOTIFS_MS = 120

# Optional simulated network latency per direction (ms)
SIMULATED_RTT_MS = 120
SIMULATED_RTT_JITTER_MS = 40
