name = "webui"
# Custom worker wraps SvelteKit output and exposes Beelay RPC WebSocket endpoint
main = "src/worker.ts"
compatibility_date = "2025-07-18"
compatibility_flags = ["nodejs_compat"]
workers_dev = true

[assets]
binding = "ASSETS"
directory = ".svelte-kit/cloudflare"

[durable_objects]
bindings = [
  { name = "BEELAY_DO", class_name = "BeelayDO" }
]

[[migrations]]
tag = "webui-v1"
new_sqlite_classes = ["BeelayDO"]
